# Generated by Django 5.1.4 on 2025-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.DateField(),
        ),
    ]
