# Generated by Django 5.1.4 on 2025-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_alter_subscription_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
